.storybook/main.ts, .storybook/preview.ts, package.json, src/stories/Button.stories.ts, src/stories/Button.tsx, src/stories/button.css, yarn.lock
- Added Storybook setup
- Added react-vite framework config
- Added button base story
Closes #2
=> 🚀 feat: added storybook setup

.storybook/preview.tsx, package.json, postcss.config.js, src/components/button.css, src/components/button.tsx, src/components/index.ts, src/stories/Button.stories.ts, tailwind.config.js, vite.config.ts, yarn.lock
Fixes #4 
Added `bg-bg` to secondary button to test on Connect.
As expected the tailwind classes override the classes on Connect. We need to think if this is as it should be or if we should scope the tailwind classes in the design system. Here is a lib that would help with that: https://github.com/dolanmiu/vite-plugin-scope-tailwind
https://github.com/powerhouse-inc/design-system/assets/5501872/fd3e33e1-eda5-41fd-9327-5d6bddec8646
=> Added initial bundle setup

.storybook/preview-body.html, package.json
- Fix storybook `body` styles
- Added `react-aria-components` as dev dependency
=> 🐞 fix: Storybook body styles

.storybook/preview.tsx, src/powerhouse/components/drag-and-drop/__snapshots__/drag-and-drop.test.tsx.snap
Fixes #30 
The initial theme was not correct on startup.
=> Fixed default storybook theme

.commitlintrc.json, .github/workflows/release.yml, .husky/commit-msg, .husky/pre-commit, .lintstagedrc.json, .releaserc, package.json, yarn.lock
- Setup github action for CD
- Added commit lint
- Added lint-staged
- Added tests check hook
=> chore(project-setup): 🚀 setup release workflow

README.md
=> docs: added readme content

src/connect/components/drive-view/drive-view.stories.tsx, src/connect/components/drive-view/drive-view.tsx, src/connect/components/tree-view-item/tree-view-item.tsx, src/powerhouse/components/sidebar/sidebar-panel.tsx, src/powerhouse/components/tree-view-item/tree-view-item.stories.tsx, src/powerhouse/components/tree-view-item/tree-view-item.tsx
- Added fade effect to `TreeViewItem` label
=> refactor: implemented fade effect for tree-view-item label

src/connect/components/tree-view-item/tree-view-item.stories.tsx, src/connect/components/tree-view-item/tree-view-item.tsx, src/connect/components/tree-view/tree-view.stories.tsx
- Enabled node selection in `ConnectTreeViewItem`
=> feat(tree-view-item): 🚀 enabled node selection

.eslintignore, package.json, src/connect/components/sidebar/__snapshots__/sidebar.test.tsx.snap, src/connect/components/sidebar/sidebar-footer.tsx, src/connect/components/sidebar/sidebar-header.tsx, src/connect/components/sidebar/sidebar-user.tsx, src/connect/components/sidebar/sidebar.tsx, src/powerhouse/components/sidebar/__snapshots__/sidebar.test.tsx.snap, src/powerhouse/components/sidebar/sidebar.tsx, src/powerhouse/hooks/animation.ts, tailwind.config.js, yarn.lock
https://github.com/powerhouse-inc/design-system/assets/5501872/b9ce54be-3f7e-480f-a820-40bb2db941bd
Fixes #42
=> feat: added sidebar collapse animation

src/connect/components/drive-view/drive-view.stories.tsx, src/connect/components/drive-view/drive-view.tsx, src/connect/components/sidebar/__snapshots__/sidebar.test.tsx.snap, src/connect/components/sidebar/sidebar-user.tsx, src/connect/components/sidebar/sidebar.stories.tsx
Added drive to event callbacks to make it easier to distinguish between drives.
=> refactor: updated DriveView props and events

src/connect/components/index.ts, src/connect/components/modal/__snapshots__/delete-item-modal.test.tsx.snap, src/connect/components/modal/delete-item-modal.stories.tsx, src/connect/components/modal/delete-item-modal.test.tsx, src/connect/components/modal/delete-item-modal.tsx, src/connect/components/modal/index.ts, src/powerhouse/components/index.ts, src/powerhouse/components/modal/__snapshots__/modal.test.tsx.snap, src/powerhouse/components/modal/index.ts, src/powerhouse/components/modal/modal.stories.tsx, src/powerhouse/components/modal/modal.test.tsx, src/powerhouse/components/modal/modal.tsx, src/tailwind.css
- Added base `Modal` component
- Added `ConnectDeleteItemModal` component
=> feat(modal): 🚀 Added Modal Component

src/connect/components/drive-view/drive-view.stories.tsx, src/connect/components/drive-view/drive-view.tsx, src/connect/components/dropdown-menu/dropdown-menu.tsx, src/connect/components/sidebar/sidebar.stories.tsx, src/connect/components/tree-view-item/tree-view-item.stories.tsx, src/connect/components/tree-view-item/tree-view-item.tsx, src/connect/components/tree-view/tree-view.stories.tsx, src/connect/components/tree-view/tree-view.tsx, src/powerhouse/components/dropdown-menu/dropdown-menu.tsx
Added default options to tree item.
Added type autocomplete to item options.
https://github.com/powerhouse-inc/design-system/assets/5501872/8747ebc7-9e5a-4708-9a00-58463330a073
=> refactor: added typed default options to drive view

src/connect/components/drive-view/drive-view.tsx, src/powerhouse/hooks/useDraggableTarget.ts
- Added File drop event support
=> feat(drag-and-drop): 🚀 Added support for file drop events

src/connect/components/drive-view/drive-view.stories.tsx, src/connect/components/drive-view/drive-view.tsx, src/connect/components/tree-view-input/tree-view-input.tsx, src/connect/components/tree-view-item/tree-view-item.stories.tsx, src/connect/components/tree-view-item/tree-view-item.tsx, src/connect/components/tree-view/tree-view.stories.tsx, src/connect/components/tree-view/tree-view.tsx, src/powerhouse/components/tree-view-item/tree-view-item.tsx, src/powerhouse/hooks/useDraggableTarget.ts
- Implemented callback fn when hover in drag state (used to open a folder)
- Added support for `DragStart` and `DragEnd` events
- Fix styles
=> feat(drag-and-drop): 🚀 added support for onDropActivate + small fixes

package.json, src/connect/components/drive-view/drive-view.tsx, src/powerhouse/hooks/useDraggableTarget.ts, vite.config.ts, yarn.lock
`vite-tsconfig-path` is not compatible with `vite-plugin-dts` so types import with `@/powerhouse` were not being resolved.
Also added `dropAfterItem` and `dropBeforeItem` to file drop
=> feat: fixed dropItem export

src/connect/components/modal/__snapshots__/upgrade-drive-modal.test.tsx.snap, src/connect/components/modal/upgrade-drive-modal.stories.tsx, src/connect/components/modal/upgrade-drive-modal.test.tsx, src/connect/components/modal/upgrade-drive-modal.tsx
=> feat(modal): added upgrade drive modal

src/connect/components/drive-view/drive-view.stories.tsx, src/connect/components/drive-view/drive-view.tsx, src/connect/components/sidebar/sidebar.stories.tsx
- fix `DriveView` and `Sidebar` styles
Fixes powerhouse-inc/document-model-electron#21
=> fix: 🚀 DriveView and Sidebar styles

src/connect/components/breadcrumbs/breadcrumbs.tsx, src/connect/components/drive-view/drive-view.tsx, src/connect/components/tree-view/tree-view.tsx, src/connect/hooks/index.ts, src/connect/hooks/tree-view/usePathContent/usePathContent.ts, src/connect/index.tsx, src/connect/utils/tree-item.test.ts, src/connect/utils/tree-item.ts
- Added missing exports
- Added filter types for `DriveView`
- Added `encodeID` and `decodeID` utils (used to escape special chars in Drive IDs)
=> feat: added missing exports + filter types + encode/decode utils

src/connect/components/sidebar/__snapshots__/sidebar.test.tsx.snap, src/connect/components/sidebar/sidebar-user.tsx
- fix `SidebarUser` styles
Fixes powerhouse-inc/document-model-electron#20
=> fix: 🎨 SidebarUser styles

tailwind.config.ts
In preparation for implementing the style guide, I've converted the tailwind config file to typescript.
=> feat: convert tw config to ts

src/connect/hooks/tree-view/index.ts, src/connect/hooks/tree-view/useFilerPathContent/index.ts, src/connect/hooks/tree-view/useFilerPathContent/useFilterPathContent.test.ts, src/connect/hooks/tree-view/useFilerPathContent/useFilterPathContent.ts, src/connect/hooks/tree-view/useGetPathContent/index.ts, src/connect/hooks/tree-view/useGetPathContent/useGetPathContent.test.ts, src/connect/hooks/tree-view/useGetPathContent/useGetPathContent.ts, src/connect/hooks/tree-view/utils/getPathContent.ts, src/connect/hooks/tree-view/utils/index.ts, src/connect/utils/path.ts
- Added `useGetPathContent` hook
- Added `useFilterPathContent` hook
Note: this hooks are required for the implementation of https://github.com/powerhouse-inc/document-model-electron/issues/28
=> feat: 🚀 added useGetPathContent and useFilterPathContent hooks

src/connect/components/tree-view-item/tree-view-item.tsx, src/powerhouse/components/tree-view-input/__snapshots__/tree-view-input.test.tsx.snap, src/powerhouse/components/tree-view-input/tree-view-input.tsx
- Added default icons for `TreeViewInput`
=> feat: added default icons for TreeViewInput

src/connect/components/search-bar/__snapshots__/search-bar.test.tsx.snap, src/connect/components/sidebar/__snapshots__/sidebar.test.tsx.snap, src/powerhouse/components/icon/icon.tsx
- Removed `/` from icons url (this is causing an error when file is imported from connect build)
=> fix: removed / from icon url

src/connect/components/folder-item/__snapshots__/folder-item.test.tsx.snap, src/connect/components/folder-item/folder-item.tsx
- fix hover styles in FolderItem
=> fix: hover styles in FolderItem

src/connect/hooks/tree-view/index.ts, src/connect/hooks/tree-view/useGetItemById/index.ts, src/connect/hooks/tree-view/useGetItemById/useGetItemById.test.ts, src/connect/hooks/tree-view/useGetItemById/useGetItemById.ts
=> feat: added useGetItemById hook

src/connect/components/folder-item/__snapshots__/folder-item.test.tsx.snap, src/connect/components/folder-item/folder-item.stories.tsx, src/connect/components/folder-item/folder-item.test.tsx, src/connect/components/folder-item/folder-item.tsx
- Added `write` mode to `FolderItem` Component
=> feat: added write mode to FolderItem Component

src/globals.css, src/rwa/components/index.ts, src/rwa/components/tabs/index.ts, src/rwa/components/tabs/tabs.stories.tsx, src/rwa/components/tabs/tabs.tsx
=> feat: added RWATabs component

src/rwa/components/fees-table/fees-table.tsx, src/rwa/components/table/fixed-income-assets-table.tsx, src/rwa/components/table/header-label.tsx, src/rwa/components/table/table-cell.tsx, src/rwa/components/table/table.stories.tsx, src/rwa/components/table/table.tsx, src/rwa/components/tx-detail/tx-detail.tsx
Replace the problematic table library with vanilla html.
NOTE: the sorting function needs to be re-added
=> feat: use vanilla html table

src/rwa/components/asset-details/asset-details.stories.tsx, src/rwa/components/asset-details/asset-details.tsx, src/rwa/components/asset-details/form.ts, src/rwa/components/create-asset-form/create-asset-form.tsx, src/rwa/components/table/fixed-income-assets-table.stories.tsx, src/rwa/components/table/fixed-income-assets-table.tsx, src/rwa/components/table/table.stories.tsx, src/rwa/components/table/table.tsx, src/rwa/components/table/useSortTableItems.ts
Update fixed income asset inputs to match the schema
Fix bug where the list of sorted table items did not update when new items were added
=> feat: fix sorting behavior and update input types

src/connect/components/drive-view/drive-view.tsx, src/connect/components/form/add-public-drive-form.tsx
- use public drive form for adding cloud drives
=> feat: use public drive form for adding cloud drives

src/connect/components/file-item/file-item.stories.tsx, src/connect/components/file-item/file-item.tsx, src/connect/components/modal/index.ts, src/connect/components/modal/rename-node.stories.tsx, src/connect/components/modal/rename-node.tsx
- Added rename modal
- Added support for write mode in FileItem component
=> feat: added rename modal + support for write mode file-item

src/rwa/components/tabs/tabs.stories.tsx, src/rwa/components/tabs/tabs.tsx
- added switchboard link button to RWATabs
=> feat: added switchboard link button to RWATabs

src/connect/components/tree-view-item/tree-view-item.tsx
when an item is being edited, do not show the dropdown menu on hover.
=> feat: hide dropdown icon when is write

src/connect/components/sidebar/sidebar-footer.tsx, src/connect/components/sidebar/sidebar.tsx
- added handler for sidebar settings click
=> feat: added handler for sidebar settings click

src/connect/components/file-item/__snapshots__/file-item.test.tsx.snap, src/connect/components/file-item/file-item.stories.tsx, src/connect/components/file-item/file-item.test.tsx, src/connect/components/file-item/file-item.tsx, src/connect/components/folder-item/__snapshots__/folder-item.test.tsx.snap, src/connect/components/folder-item/folder-item.stories.tsx, src/connect/components/folder-item/folder-item.test.tsx, src/connect/components/folder-item/folder-item.tsx
- Added drag and drop options to FileItem and FolderItem
=> feat: added drag and drop options to FileItem and FolderItem

src/connect/components/drive-view/drive-view.stories.tsx, src/connect/components/drive-view/drive-view.tsx, src/connect/components/tree-view/tree-view.tsx
=> feat: allow disable add drives

src/connect/components/tree-view-item/tree-view-item.tsx
- Added selected styles for TreeViewItem
=> feat: added selected styles for TreeViewItem

src/connect/components/date-time-input/date-time-local-input.tsx, src/rwa/components/inputs/form-inputs.tsx, src/rwa/components/inputs/form-row.tsx, src/rwa/components/inputs/select.tsx, src/rwa/components/inputs/text-input.tsx, src/rwa/components/select/select.tsx, src/rwa/components/table/accounts/account-details.tsx, src/rwa/components/table/assets/asset-details.tsx, src/rwa/components/table/assets/assets-table.tsx, src/rwa/components/table/base/item-details.tsx, src/rwa/components/table/base/table-base.tsx, src/rwa/components/table/base/table.tsx, src/rwa/components/table/constants.ts, src/rwa/components/table/fixed-income-types/fixed-income-type-details.tsx, src/rwa/components/table/service-provider-fee-types/service-provider-fee-type-details.tsx, src/rwa/components/table/spvs/spv-details.tsx, src/rwa/components/table/transactions/fee-transactions-table.stories.tsx, src/rwa/components/table/transactions/fee-transactions-table.tsx, src/rwa/components/table/transactions/group-transaction-details.tsx, src/rwa/components/table/transactions/group-transactions-table.stories.tsx, src/rwa/components/table/transactions/group-transactions-table.tsx, src/rwa/components/table/transactions/service-provider-fee-type-table-input.tsx, src/rwa/components/table/types.ts, src/rwa/components/table/utils.tsx, src/rwa/mocks/transactions.ts, src/rwa/types/index.ts, src/rwa/utils/index.ts, src/shared-tailwind.config.ts
implement further feedback from teep, and implement design updates from willow.
- update alignment of fields in table forms
- add delete button to table item forms
- change position of "Total discount" column in assets table
- replace account id with account reference in service provider table/form
- show purchase transactions as having negative cash amounts and sales as having negative quantity amounts in transactions table
- make dropdown menu options the same width as the dropdown button
=> feat: implement teep's feedback 3

src/rwa/components/table/assets/assets-table.stories.tsx, src/rwa/components/table/assets/assets-table.tsx, src/rwa/components/table/base/table-base.tsx, src/rwa/components/table/base/table.tsx, src/rwa/components/table/transactions/group-transactions-table.tsx, src/rwa/components/table/types.ts, src/rwa/mocks/assets.ts, src/rwa/types/index.ts
add a row that shows the cash asset balance at the top of the assets table
=> feat: add cash asset row

src/connect/components/folder-item/folder-item.stories.tsx, src/connect/components/folder-item/folder-item.tsx
I missed one of the items that need to have buttons disabled
=> feat: add allow param to folder item

src/rwa/components/table/accounts/accounts-table.stories.tsx, src/rwa/components/table/assets/assets-table.stories.tsx, src/rwa/components/table/base/item-details.tsx, src/rwa/components/table/base/table.tsx, src/rwa/components/table/fixed-income-types/fixed-income-types-table.stories.tsx, src/rwa/components/table/service-provider-fee-types/service-provider-fee-types-table.stories.tsx, src/rwa/components/table/spvs/spvs-table.stories.tsx, src/rwa/components/table/transactions/group-transactions-table.stories.tsx, src/rwa/components/table/types.ts
pass is allowed to edit and is allowed to create props down to table components.
hide edit buttons when not allowed to edit.
hide create buttons when not allowed to create.
=> feat: handle rwa allow list

src/rwa/components/table/accounts/account-details.tsx, src/rwa/components/table/accounts/accounts-table.stories.tsx, src/rwa/components/table/accounts/accounts-table.tsx, src/rwa/components/table/base/item-details.tsx, src/rwa/components/table/base/table.tsx, src/rwa/components/table/types.ts, src/rwa/components/table/utils.tsx, src/rwa/mocks/assets.ts
- prevent users from deleting the principal lender account in the accounts table
- add a label that says "Lender" to show the user that this account is the principal lender
=> feat: handle principal lender

src/connect/components/combobox/combobox.tsx, src/rwa/components/inputs/select.tsx, src/rwa/components/table/assets/asset-details.tsx, src/rwa/components/table/base/item-details.tsx, src/rwa/components/table/service-provider-fee-types/service-provider-fee-type-details.tsx, src/rwa/components/table/transactions/group-transaction-details.tsx, src/rwa/components/table/transactions/group-transactions-table.stories.tsx
We need the RWA select component to allow scroll and to allow searching.
Replace the underlying select component with the one used in the filter by assets since it already supports these.
=> feat: use combobox in rwa select

src/connect/components/drive-view/drive-view.stories.tsx, src/connect/components/drive-view/drive-view.tsx, src/connect/components/file-item/__snapshots__/file-item.test.tsx.snap, src/connect/components/file-item/file-item.stories.tsx, src/connect/components/file-item/file-item.tsx, src/connect/components/folder-item/__snapshots__/folder-item.test.tsx.snap, src/connect/components/folder-item/folder-item.stories.tsx, src/connect/components/folder-item/folder-item.tsx, src/connect/components/tree-view-item/tree-view-item.tsx, src/connect/components/tree-view/tree-view.tsx, src/connect/utils/get-folder-status.test.ts, src/connect/utils/get-folder-status.ts, src/connect/utils/index.ts
- enabled sync icon for files and folders
=> feat: enabled sync icon for files and folders

src/connect/components/file-item/file-item.tsx, src/connect/components/folder-item/folder-item.tsx, src/connect/components/status-icon/sync-status-icon.tsx, src/connect/components/tree-view-item/tree-view-item.tsx, src/powerhouse/components/tree-view-item/tree-view-item.tsx
- use checkmark icon for success sync status in folders and files
=> feat: use checkmark icon for success sync status in folders and files

src/rwa/components/table/constants.ts, src/rwa/components/table/transactions/useGroupTransactionForm.tsx, src/rwa/components/table/types/form.ts, src/rwa/constants/transactions.ts
add options for income transaction types.
=> feat: add income transaction types

src/rwa/components/table/accounts/accounts-table.tsx, src/rwa/components/table/assets/assets-table.tsx, src/rwa/components/table/base/table.tsx, src/rwa/components/table/base/use-table-height.ts, src/rwa/components/table/fixed-income-types/fixed-income-types-table.tsx, src/rwa/components/table/service-provider-fee-types/service-provider-fee-types-table.tsx, src/rwa/components/table/spvs/spvs-table.tsx, src/rwa/components/table/transactions/fee-transactions-table.stories.tsx, src/rwa/components/table/transactions/fee-transactions-table.tsx, src/rwa/components/table/transactions/group-transaction-details.tsx, src/rwa/components/table/transactions/group-transactions-table.tsx, src/rwa/components/table/transactions/useGroupTransactionForm.tsx, src/rwa/components/table/types/form.ts, src/rwa/components/table/types/table.ts, src/rwa/mocks/transactions.ts, src/rwa/types/index.ts
=> feat: add type field and service provider input

src/connect/components/revision-history/skip/index.ts, src/connect/components/revision-history/skip/skip.stories.tsx, src/connect/components/revision-history/skip/skip.tsx
add component for displaying skipped revisions
=> feat: add skip component

src/rwa/components/tabs/tabs.tsx
=> feat: remove placeholder space

src/connect/components/status-icon/sync-status-icon.tsx, src/connect/constants/syncing.ts
- Enabled `INITIAL_SYNC` status
=> feat: enabled INITIAL_SYNC status

src/rwa/components/table/assets/assets-table.tsx
- remove notional total from RWA Assets Table
=> feat: remove notional total

src/connect/components/revision-history/header/scope.tsx, src/connect/components/revision-history/revision-history.tsx, src/connect/components/revision-history/timeline/timeline.tsx, src/powerhouse/components/index.ts, src/powerhouse/components/pagination/index.ts, src/powerhouse/components/pagination/pagination-button.tsx, src/powerhouse/components/pagination/pagination.stories.tsx, src/powerhouse/components/pagination/pagination.tsx, src/powerhouse/hooks/index.ts, src/powerhouse/hooks/usePagination.test.ts, src/powerhouse/hooks/usePagination.ts, src/rwa/components/table/assets/assets-table.tsx, src/rwa/components/table/transactions/group-transactions-table.tsx
- Added pagination to RWA tables and revision history
=> 328 pagination filtering designs for revision history

src/connect/components/cookie-banner/cookie-banner.stories.tsx, src/connect/components/cookie-banner/cookie-banner.tsx, src/connect/components/cookie-banner/index.ts, src/connect/components/index.ts
- Added `CookieBanner` component
=> feat: added CookieBanner component

src/connect/components/revision-history/revision-history.stories.tsx, src/connect/components/revision-history/revision-history.tsx, src/connect/components/revision-history/revision/revision-number.stories.tsx, src/connect/components/revision-history/skip-operations.json, src/connect/components/revision-history/skip/skip.tsx, src/connect/components/revision-history/timeline/timeline.stories.tsx, src/connect/components/revision-history/utils.ts
=> fix: #376 skipped operations on revision history

src/connect/components/modal/settings-modal/dependency-versions/dependency-versions.tsx
Connect now defines all dependencies as devDependencies since they are only needed on build time.
=> fix: updated dependencies check to check Connect dev dependencies
